export const TRIVIA_QUESTIONS = [
  { q: "Who is the supreme head of the Malankara Orthodox Syrian Church?", options: ["The Pope", "Catholicos of the East", "Patriarch of Antioch", "Archbishop of Canterbury"], a: "Catholicos of the East" },
  { q: "Which Apostle is believed to have brought Christianity to Kerala, India?", options: ["St. Peter", "St. Paul", "St. Thomas", "St. Andrew"], a: "St. Thomas" },
  { q: "In what year is St. Thomas believed to have landed in Kerala?", options: ["AD 33", "AD 52", "AD 70", "AD 325"], a: "AD 52" },
  { q: "What is the primary liturgical language traditionally used in the Malankara Orthodox Church?", options: ["Latin", "Greek", "Syriac", "Hebrew"], a: "Syriac" },
  { q: "What is the Holy Communion called in the Orthodox tradition?", options: ["Mass", "Qurbana", "Eucharist", "Liturgy"], a: "Qurbana" },
  { q: "How many sacraments are officially recognized in the Orthodox Church?", options: ["2", "3", "7", "9"], a: "7" },
  { q: "Which ecumenical council is NOT accepted by the Oriental Orthodox Churches?", options: ["Nicaea", "Constantinople", "Ephesus", "Chalcedon"], a: "Chalcedon" },
  { q: "Who is the saint popularly known as 'Parumala Thirumeni'?", options: ["St. Gregorios of Parumala", "St. Dionysius", "St. Baselios", "St. Thomas"], a: "St. Gregorios of Parumala" },
  { q: "What is the 50-day lent before Easter called in the Orthodox Church?", options: ["Advent", "Great Lent", "Nineveh Fast", "Apostles' Fast"], a: "Great Lent" },
  { q: "What is the Syriac word for 'Peace be with you' used in the Liturgy?", options: ["Shlomo", "Aloho", "Barekmor", "Kurielaison"], a: "Shlomo" },
  { q: "What does 'Barekmor' mean?", options: ["Lord have mercy", "Bless, O Lord", "Praise to God", "Peace to you"], a: "Bless, O Lord" },
  { q: "Which council formulated the Nicene Creed?", options: ["Council of Nicaea", "Council of Ephesus", "Council of Trent", "Council of Chalcedon"], a: "Council of Nicaea" },
  { q: "What is the term for the sanctuary in an Orthodox Church?", options: ["Nave", "Madbaha", "Bema", "Narthex"], a: "Madbaha" },
  { q: "Who wrote the majority of the Psalms?", options: ["Solomon", "Moses", "David", "Asaph"], a: "David" },
  { q: "What is the name of the traditional lamp used in Kerala churches?", options: ["Menorah", "Nilavilakku", "Thoookkuvilakku", "Kuthuvilakku"], a: "Nilavilakku" },
  { q: "Which Old Testament prophet was swallowed by a great fish?", options: ["Elijah", "Elisha", "Jonah", "Daniel"], a: "Jonah" },
  { q: "What is the shortest verse in the Bible?", options: ["Jesus wept.", "God is love.", "Pray continually.", "Rejoice always."], a: "Jesus wept." },
  { q: "What does 'Kurielaison' mean?", options: ["Praise the Lord", "Lord, have mercy", "Holy is God", "Glory to God"], a: "Lord, have mercy" },
  { q: "Who was the first Catholicate of the East established in India (1912)?", options: ["Baselios Paulose I", "Baselios Geevarghese I", "Baselios Marthoma Mathews I", "Baselios Marthoma Paulose II"], a: "Baselios Paulose I" },
  { q: "Which fast commemorates the fasting of the people of Nineveh?", options: ["Great Lent", "3 Days Fast (Moonnu Nombu)", "Apostles' Fast", "Assumption Fast"], a: "3 Days Fast (Moonnu Nombu)" },
  { q: "What does 'Orthodox' mean?", options: ["Strict belief", "True Worship/Right Belief", "Ancient way", "Eastern faith"], a: "True Worship/Right Belief" },
  { q: "Who is the mother of Jesus Christ, highly venerated in the Orthodox Church?", options: ["St. Mary (Theotokos)", "St. Elizabeth", "St. Anna", "St. Martha"], a: "St. Mary (Theotokos)" },
  { q: "What is the Syriac word for Holy Spirit?", options: ["Ruho Qadisho", "Sleebo", "Qurbono", "Thronos"], a: "Ruho Qadisho" },
  { q: "What is the traditional vestment worn by Orthodox priests during Qurbana called?", options: ["Kappa", "Phaino", "Kuthoono", "Zunoro"], a: "Phaino" },
  { q: "Where was Jesus born?", options: ["Nazareth", "Jerusalem", "Bethlehem", "Galilee"], a: "Bethlehem" },
  { q: "Who was the father of King Solomon?", options: ["Saul", "David", "Jesse", "Samuel"], a: "David" },
  { q: "Which book of the Bible contains the story of the parting of the Red Sea?", options: ["Genesis", "Exodus", "Leviticus", "Numbers"], a: "Exodus" },
  { q: "What is the meaning of the Syriac word 'Sleeba'?", options: ["Cross", "Peace", "Light", "Faith"], a: "Cross" },
  { q: "Who was the first Christian martyr?", options: ["St. Peter", "St. Paul", "St. Stephen", "St. James"], a: "St. Stephen" },
  { q: "Which liturgical season begins the Church calendar in the Syrian Orthodox tradition?", options: ["Kudosh Edto", "Advent", "Great Lent", "Pentecost"], a: "Kudosh Edto" },
  { q: "In the Parable of the Prodigal Son, what does the father give the returning son first?", options: ["A gold coin", "A robe and ring", "A staff", "A pair of oxen"], a: "A robe and ring" },
  { q: "Which Old Testament book contains the prophecy of the suffering servant?", options: ["Jeremiah", "Ezekiel", "Isaiah", "Daniel"], a: "Isaiah" },
  { q: "Which apostle replaced Judas Iscariot?", options: ["Matthias", "Barnabas", "Paul", "Silas"], a: "Matthias" },
  { q: "What is the Syriac name for the altar table in the sanctuary?", options: ["Madbaha", "Thronos", "Phaino", "Bema"], a: "Thronos" },
  { q: "Which book of the Bible comes after the Gospels and describes the early Church?", options: ["Romans", "Revelation", "Acts of the Apostles", "Hebrews"], a: "Acts of the Apostles" },
  { q: "Which feast commemorates Christ's baptism in the Jordan River?", options: ["Denaha (Epiphany)", "Christmas", "Easter", "Ascension"], a: "Denaha (Epiphany)" },
  { q: "Who was the father of John the Baptist?", options: ["Zechariah", "Simeon", "Eli", "Joseph"], a: "Zechariah" },
  { q: "What is the name of the circular host of bread used for the Holy Qurbana?", options: ["Manna", "Phaino", "Buhro", "Baskomo"], a: "Buhro" },
  { q: "Which book of the Bible is the longest by word count?", options: ["Psalms", "Genesis", "Jeremiah", "Isaiah"], a: "Jeremiah" },
  { q: "How many days did Jesus fast in the wilderness?", options: ["3 days", "7 days", "40 days", "50 days"], a: "40 days" },
  { q: "Which feast celebrates the descent of the Holy Spirit on the Apostles?", options: ["Pentecost", "Ascension", "Transfiguration", "Easter"], a: "Pentecost" },
  { q: "What was the name of the garden where Jesus prayed before His crucifixion?", options: ["Eden", "Gethsemane", "Golgotha", "Sinai"], a: "Gethsemane" },
  { q: "Who was the first king of Israel?", options: ["David", "Saul", "Solomon", "Rehoboth"], a: "Saul" },
  { q: "What is the meaning of the name 'Emmanuel'?", options: ["God is great", "God with us", "God forgives", "God saves"], a: "God with us" },
  { q: "Which Old Testament book tells the story of a Queen who saved her people?", options: ["Ruth", "Esther", "Judith", "Song of Solomon"], a: "Esther" },
  { q: "What is the name of the prayer oil used for anointing in Baptism?", options: ["Myron", "Frankincense", "Olive oil", "Chrism"], a: "Myron" },
  { q: "Which gospel writer was a physician by profession?", options: ["St. Matthew", "St. Mark", "St. Luke", "St. John"], a: "St. Luke" },
  { q: "How many times does Jesus tell us to forgive our brother?", options: ["Seven times", "Seventy times", "Seventy times seven", "Always"], a: "Seventy times seven" },
  { q: "What is the term for the vestment worn around the neck by priests, symbolizing the yoke of Christ?", options: ["Kappa", "Hamnikho", "Zunoro", "Phaino"], a: "Hamnikho" },
  { q: "Which of these is the traditional Syriac title for the Virgin Mary meaning 'Mother of God'?", options: ["Theotokos", "Yoldath Aloho", "Shmuni", "Bath Qyama"], a: "Yoldath Aloho" },

  // New Questions Added (50 additional high quality questions)
  { q: "How many books are in the Protestant Bible?", options: ["66", "73", "81", "39"], a: "66" },
  { q: "How many books are in the Orthodox Bible (including Deuterocanon)?", options: ["66", "73", "81", "27"], a: "81" },
  { q: "Who was the oldest man mentioned in the Bible?", options: ["Adam", "Methuselah", "Noah", "Abraham"], a: "Methuselah" },
  { q: "Who was thrown into the lions' den for praying to God?", options: ["Jeremiah", "Daniel", "Shadrach", "Ezekiel"], a: "Daniel" },
  { q: "Which disciple is known in the Gospel of John as the 'beloved disciple'?", options: ["Peter", "James", "John", "Andrew"], a: "John" },
  { q: "In which city were the disciples first called 'Christians'?", options: ["Jerusalem", "Rome", "Antioch", "Damascus"], a: "Antioch" },
  { q: "Who was chosen to lead the Israelites after the death of Moses?", options: ["Aaron", "Caleb", "Joshua", "Eleazar"], a: "Joshua" },
  { q: "On which mountain did Moses receive the Ten Commandments?", options: ["Mount Carmel", "Mount Sinai", "Mount Ararat", "Mount Nebo"], a: "Mount Sinai" },
  { q: "Who was the wife of Abraham and mother of Isaac?", options: ["Sarah", "Rebekah", "Rachel", "Leah"], a: "Sarah" },
  { q: "Who was the mother of the prophet Samuel?", options: ["Hannah", "Peninnah", "Elizabeth", "Ruth"], a: "Hannah" },
  { q: "Which prophet was taken up to heaven in a chariot of fire?", options: ["Elisha", "Elijah", "Isaiah", "Moses"], a: "Elijah" },
  { q: "Which short tax collector climbed a sycamore tree to see Jesus?", options: ["Matthew", "Zacchaeus", "Levi", "Zebedee"], a: "Zacchaeus" },
  { q: "On which island was John when he wrote the Book of Revelation?", options: ["Crete", "Cyprus", "Patmos", "Malta"], a: "Patmos" },
  { q: "How many days was Lazarus in the tomb before Jesus raised him?", options: ["1 day", "2 days", "3 days", "4 days"], a: "4 days" },
  { q: "What was the trade or profession of the Apostle Paul?", options: ["Fisherman", "Tentmaker", "Tax collector", "Physician"], a: "Tentmaker" },
  { q: "Which Bible book describes rebuilding the walls of Jerusalem?", options: ["Ezra", "Nehemiah", "Esther", "Haggai"], a: "Nehemiah" },
  { q: "Who was the first person to see the resurrected Jesus?", options: ["Simon Peter", "John", "Mary Magdalene", "Mother Mary"], a: "Mary Magdalene" },
  { q: "In what language was the Old Testament originally written?", options: ["Hebrew", "Greek", "Latin", "Syriac"], a: "Hebrew" },
  { q: "In what language was the New Testament originally written?", options: ["Hebrew", "Greek", "Aramaic", "Latin"], a: "Greek" },
  { q: "In which town did Jesus perform His first miracle, turning water to wine?", options: ["Cana", "Nazareth", "Capernaum", "Bethsaida"], a: "Cana" },
  { q: "Who was the wife of Isaac?", options: ["Sarah", "Rebekah", "Rachel", "Leah"], a: "Rebekah" },
  { q: "Who was Joseph's youngest brother, whom he loved dearly?", options: ["Reuben", "Simeon", "Judah", "Benjamin"], a: "Benjamin" },
  { q: "Which apostle denied knowing Jesus three times before the rooster crowed?", options: ["Judas", "Thomas", "Peter", "Philip"], a: "Peter" },
  { q: "What is the symbol of God's covenant with Noah after the flood?", options: ["An altar", "A rainbow", "A dove", "An olive branch"], a: "A rainbow" },
  { q: "Who was the giant philistine warrior defeated by young David?", options: ["Goliath", "Og", "Sihon", "Delilah"], a: "Goliath" },
  { q: "Which prophet was thrown into a muddy cistern for preaching God's word?", options: ["Elijah", "Jeremiah", "Ezekiel", "Isaiah"], a: "Jeremiah" },
  { q: "What did John the Baptist eat in the wilderness?", options: ["Bread and fish", "Locusts and wild honey", "Manna", "Figs and dates"], a: "Locusts and wild honey" },
  { q: "Who was the Roman governor who sentenced Jesus to crucifixion?", options: ["Herod", "Pontius Pilate", "Felix", "Festus"], a: "Pontius Pilate" },
  { q: "Who was the first high priest of Israel?", options: ["Moses", "Aaron", "Melchizedek", "Eleazar"], a: "Aaron" },
  { q: "How many plagues did God send upon Egypt?", options: ["7", "10", "12", "40"], a: "10" },
  { q: "Which sea did the Israelites cross on dry land to escape Pharaoh?", options: ["Dead Sea", "Red Sea", "Sea of Galilee", "Mediterranean Sea"], a: "Red Sea" },
  { q: "What is the Greek word for 'Anointed One', translating to 'Messiah'?", options: ["Adonai", "Christos", "Kurios", "Elohim"], a: "Christos" },
  { q: "On which day of creation did God make the sun, moon, and stars?", options: ["First day", "Third day", "Fourth day", "Sixth day"], a: "Fourth day" },
  { q: "What is the first commandment that includes a promise?", options: ["No other gods", "Do not steal", "Honor your father and mother", "Remember the Sabbath"], a: "Honor your father and mother" },
  { q: "Which prophet saw a vision of a valley of dry bones coming to life?", options: ["Isaiah", "Jeremiah", "Ezekiel", "Hosea"], a: "Ezekiel" },
  { q: "Who was the wealthy landowner that Ruth married?", options: ["Boaz", "Elimelech", "Mahlon", "Jesse"], a: "Boaz" },
  { q: "What was the name of Moses' sister?", options: ["Zipporah", "Miriam", "Leah", "Hannah"], a: "Miriam" },
  { q: "Which book of the Old Testament contains the story of the tower of Babel?", options: ["Genesis", "Exodus", "Numbers", "Deuteronomy"], a: "Genesis" },
  { q: "Who was Israel's last judge and first major prophet?", options: ["Gideon", "Samson", "Samuel", "Eli"], a: "Samuel" },
  { q: "Which gospel is focused heavily on showing Jesus as the fulfillment of Jewish prophecy?", options: ["Matthew", "Mark", "Luke", "John"], a: "Matthew" },
  { q: "What does the word 'Gospel' literally mean?", options: ["Good News", "Holy Writing", "Truth", "Word of God"], a: "Good News" },
  { q: "Which of Jesus' disciples was a tax collector before he was called?", options: ["Peter", "Matthew", "John", "Simon the Zealot"], a: "Matthew" },
  { q: "Who wrote the Acts of the Apostles?", options: ["Paul", "Luke", "Peter", "John"], a: "Luke" },
  { q: "In the Bible, who is known for having extreme patience during suffering?", options: ["Job", "Abraham", "David", "Joseph"], a: "Job" },
  { q: "What city was surrounded and collapsed after the Israelites marched around it?", options: ["Jericho", "Ai", "Gibeon", "Babylon"], a: "Jericho" },
  { q: "Which prophet ran from God and ended up in Nineveh after being redirected?", options: ["Amos", "Jonah", "Micah", "Obadiah"], a: "Jonah" },
  { q: "Who was the father of John the Baptist?", options: ["Zechariah", "Joseph", "Simeon", "Levi"], a: "Zechariah" },
  { q: "What was the primary language Jesus spoke in His daily life?", options: ["Greek", "Latin", "Hebrew", "Aramaic"], a: "Aramaic" },
  { q: "Which book of the Bible is primarily a collection of wise sayings?", options: ["Psalms", "Proverbs", "Ecclesiastes", "Job"], a: "Proverbs" },
  { q: "What was the name of Abraham's son born to Hagar?", options: ["Isaac", "Ishmael", "Jacob", "Esau"], a: "Ishmael" }
];

export function getRandomTrivia() {
  const randomIndex = Math.floor(Math.random() * TRIVIA_QUESTIONS.length);
  return TRIVIA_QUESTIONS[randomIndex];
}

// Ensure array is shuffled if requested as a list
export function getShuffledTrivia() {
  const shuffled = [...TRIVIA_QUESTIONS];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
}
